# Generated by Django 4.2.1 on 2024-11-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('physical', 'Physical Abuse'), ('emotional', 'Emotional Abuse'), ('financial', 'Financial Abuse'), ('other', 'Other')], max_length=20)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
