# Generated by Django 4.2.1 on 2024-12-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
